import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { createClient } from "@/lib/supabase/server";
import { cookies } from "next/headers";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies()
  const supabase = createClient(cookieStore)
  const { data: { user } } = await supabase.auth.getUser()

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav style={{ padding: '10px', borderBottom: '1-px solid #ccc', display: 'flex', justifyContent: 'space-between' }}>
          <Link href="/">Home</Link>
          <div>
            {user ? (
              <div style={{ display: 'flex', alignItems: 'center' }}>
                <span style={{ marginRight: '10px' }}>{user.email}</span>
                <form action="/auth/signout" method="post">
                  <button type="submit">Sign Out</button>
                </form>
              </div>
            ) : (
              <div>
                <Link href="/login" style={{ marginRight: '10px' }}>Login</Link>
                <Link href="/signup">Sign Up</Link>
              </div>
            )}
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
